apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minikube-root-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/MartinS984/weather-traffic-gitops.git'
    targetRevision: HEAD
    path: clusters/minikube
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true