apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-producer
  namespace: default
  labels:
    app: telemetry-producer
spec:
  replicas: 1 # We only need one sensor running for now
  selector:
    matchLabels:
      app: telemetry-producer
  template:
    metadata:
      labels:
        app: telemetry-producer
    spec:
      containers:
        - name: node-producer
          image: martins984/weather-traffic-producer:v1.0.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"