apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-kafka-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/MartinS984/weather-traffic-gitops.git'
    targetRevision: HEAD
    path: apps/kafka
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true